### ISSUE TITLE
分词成功，创建索引失败，提示ProcedureNotFound

### ISSUE THREAD

**Issue by climaxSun** [crazyyanchao/ongdb-lab-apoc#9]
![image](https://user-images.githubusercontent.com/49860946/226875293-33e26398-d2d5-45b1-a85a-c0aed98130d5.png)
![image](https://user-images.githubusercontent.com/49860946/226875522-229bed7e-c798-4d6c-971a-419574829976.png)

**Comment by crazyyanchao** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by crazyyanchao** [comment]
@climaxSun 该插件库已经放弃维护，如有需求可以fork后修改源码使用。
建议关注长期维护的ONgDB应用组件库：https://github.com/ongdb-contrib/ongdb-lab-apoc
